name: CI

on:
  push:
    branches:
      - main
      - beta
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run lint

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run build-storybook

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4.1.9

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 12
          - 14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - run: npm i
      - run: npm run test --ci --coverage --maxWorkers=2

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs:
      - lint
      - storybook
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i
      - name: Run Sematic release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
