name: CI

on:
  push:
    branches:
      - main
      - beta
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - eslint
          - prettier
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - run: yarn
      - run: yarn lint:${{ matrix.linter }}

  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: yarn
      - run: yarn build-storybook

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2.2.3

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 10
          - 12
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node_version }}

      - run: yarn
      - run: yarn test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs:
      - lint
      - storybook
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
      - run: yarn
      - name: Run Sematic release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
